# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

init:
- git config --global core.autocrlf input

shallow_clone: true

# https://www.appveyor.com/docs/windows-images-software/
image: Visual Studio 2019

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  CONFIGURATION: RelWithDebInfo
  matrix:
  - job_name: msvc32
    CMAKE_GENERATOR: "Visual Studio 16 2019"
    CMAKE_TOOLSET: "Win32"
    QT5: C:\Qt\5.14\msvc2017
  - job_name: msvc64
    CMAKE_GENERATOR: "Visual Studio 16 2019"
    CMAKE_TOOLSET: "x64"
    QT5: C:\Qt\5.14\msvc2017_64

matrix:
  fast_finish: true

before_build:
- set Path=C:\Python36;%Path%
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -A "%CMAKE_TOOLSET%" "-DCMAKE_PREFIX_PATH=%QT5%" -DENABLE_GUI=ON

build_script:
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

after_build:
- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%

artifacts:
- path: build/apitrace-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: gjIEc0c2BefRL7rHhypJA57Swohq5bTnyJoqT6U7jSzPiYc5GS5pt8jfKoChIzuE
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
