# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
    - /^github.*$/

init:
  - git config --global core.autocrlf input

shallow_clone: true

cache:
 - 5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86.7z
 - 5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z

# https://www.appveyor.com/docs/windows-images-software/
image: Visual Studio 2019

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - job_name: msvc32
      TARGET: win32
    - job_name: msvc64
      TARGET: win64

matrix:
  fast_finish: true

before_build:
  - set Path=C:\Python36;%Path%

build_script:
  - ps: .\ci\build-msvc.ps1 -target $Env:TARGET

artifacts:
  - path: build/apitrace-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: gjIEc0c2BefRL7rHhypJA57Swohq5bTnyJoqT6U7jSzPiYc5GS5pt8jfKoChIzuE
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
