# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

init:
- git config --global core.autocrlf input

shallow_clone: true

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
    QT5: C:\Qt\5.6\msvc2015
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    QT5: C:\Qt\5.6\msvc2015_64

matrix:
  fast_finish: true

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DCMAKE_SYSTEM_VERSION=10.0 "-DCMAKE_PREFIX_PATH=%QT5%" -DENABLE_GUI=ON

build_script:
- if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

after_build:
- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%

artifacts:
- path: build/apitrace-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: a79IHXDoZN60ADwPX1OfJYJUjaWSeKWqFfQu+531AaSuH5a03sR8ZKeNWutklAQU
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
